import { Customer, Supplier, Product, SalesInvoice, SyncLog } from '@/types/farmstack'

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    kannada_name: 'ರಾಜೇಶ್ ಕುಮಾರ್',
    phone: '9876543210',
    address: '123 Market Street, Bangalore',
    kannada_address: '123 ಮಾರುಕಟ್ಟೆ ಸಾಲು, ಬೆಂಗಳೂರು',
    gstin: '29AABCT1234H1Z0',
    tally_ledger_name: 'Rajesh Kumar',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    kannada_name: 'ಪ್ರಿಯಾ ಶರ್ಮ',
    phone: '9876543211',
    address: '456 Farm Road, Mysore',
    kannada_address: '456 ಫಾರ್ಮ್ ರಸ್ತೆ, ಮೈಸೂರು',
    gstin: '29AABCU1234H1Z0',
    tally_ledger_name: 'Priya Sharma',
  },
  {
    id: '3',
    name: 'Gopal Reddy',
    kannada_name: 'ಗೋಪಾಲ್ ರೆಡ್ಡಿ',
    phone: '9876543212',
    address: '789 Village Street, Tumkur',
    kannada_address: '789 ಹಳ್ಳಿ ಸಾಲು, ತುಮ್ಕೂರು',
    gstin: '29AABCV1234H1Z0',
    tally_ledger_name: 'Gopal Reddy',
  },
  {
    id: '4',
    name: 'Anjali Singh',
    kannada_name: 'ಅಂಜಲಿ ಸಿಂಗ್',
    phone: '9876543213',
    address: '321 Commerce Lane, Delhi',
    kannada_address: '321 ವಾಣಿಜ್ಯ ಸಾಲು, ದೆಹಲಿ',
    gstin: '29AABCZ1234H1Z0',
    tally_ledger_name: 'Anjali Singh',
  },
  {
    id: '5',
    name: 'Vikram Patel',
    kannada_name: 'ವಿಕ್ರಮ್ ಪಟೇಲ್',
    phone: '9876543214',
    address: '654 Trade Street, Ahmedabad',
    kannada_address: '654 ವ್ಯಾಪಾರ ಸಾಲು, ಅಹಮದಾಬಾದ್',
    gstin: '29AABCY1234H1Z0',
    tally_ledger_name: 'Vikram Patel',
  },
  {
    id: '6',
    name: 'Neha Gupta',
    kannada_name: 'ನೇಹಾ ಗುಪ್ತ',
    phone: '9876543215',
    address: '987 Business Park, Mumbai',
    kannada_address: '987 ವ್ಯವಸಾಯ ಪಾರ್ಕ್, ಮುಂಬೈ',
    gstin: '29AABCW1234H1Z1',
    tally_ledger_name: 'Neha Gupta',
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'AgroSupply Ltd',
    kannada_name: 'ಅಗ್ರೋ ಸರಬರಾಜು ಲಿ.',
    phone: '9876543220',
    address: '100 Industrial Area, Bangalore',
    kannada_address: '100 ಕೈಗಾರಿಕ ಪ್ರದೇಶ, ಬೆಂಗಳೂರು',
    gstin: '29AABCW1234H1Z0',
    tally_ledger_name: 'AgroSupply Ltd',
  },
  {
    id: '2',
    name: 'FarmPro Traders',
    kannada_name: 'ಫಾರ್ಮ್ ಪ್ರೋ ವ್ಯಾಪಾರಿಗಳು',
    phone: '9876543221',
    address: '200 Trade Center, Pune',
    kannada_address: '200 ವ್ಯಾಪಾರ ಕೇಂದ್ರ, ಪುಣೆ',
    gstin: '29AABCX1234H1Z0',
    tally_ledger_name: 'FarmPro Traders',
  },
  {
    id: '3',
    name: 'Green Harvest Supplies',
    kannada_name: 'ಹಸುರ ಸುಗ್ರಹ ಸರಬರಾಜು',
    phone: '9876543222',
    address: '150 Industrial Park, Coimbatore',
    kannada_address: '150 ಕೈಗಾರಿಕ ಪಾರ್ಕ್, ಕೋಯಂಬೇ',
    gstin: '29AABCU1234H1Z1',
    tally_ledger_name: 'Green Harvest Supplies',
  },
  {
    id: '4',
    name: 'Organic Seeds Co',
    kannada_name: 'ಜೈವ ಬೀಜ ಕಿ',
    phone: '9876543223',
    address: '300 Garden Lane, Indore',
    kannada_address: '300 ಮಾದ್ಯಮ ಸಾಲು, ಇಂದೋರ್',
    gstin: '29AABCV1234H1Z1',
    tally_ledger_name: 'Organic Seeds Co',
  },
  {
    id: '5',
    name: 'Premium Fertilizers',
    kannada_name: 'ಪ್ರೀಮಿಯಮ್ ರಸಗೊಬ್ಬರ',
    phone: '9876543224',
    address: '450 Chemical Zone, Surat',
    kannada_address: '450 ರಾಸಾಯನಿಕ ವಲಯ, ಸೂರತ್',
    gstin: '29AABCT1234H1Z1',
    tally_ledger_name: 'Premium Fertilizers',
  },
  {
    id: '6',
    name: 'Bio Solutions Ltd',
    kannada_name: 'ಜೈವ ಪರಿಹಾರ ಲಿ.',
    phone: '9876543225',
    address: '500 Bio Park, Jaipur',
    kannada_address: '500 ಜೈವ ಪಾರ್ಕ್, ಜೈಪುರ್',
    gstin: '29AABCS1234H1Z1',
    tally_ledger_name: 'Bio Solutions Ltd',
  },
]

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Organic Rice',
    kannada_name: 'ಆರ್ಗೆನಿಕ್ ಅಕ್ಕಿ',
    hsn_code: '1006',
    unit: 'Kg',
    product_type: 'Grain',
    maintain_batches: true,
    tally_stock_item_name: 'Organic Rice',
  },
  {
    id: '2',
    name: 'Wheat Flour',
    kannada_name: 'ಗೋಧಿ ಹಿಟ್ಟು',
    hsn_code: '1101',
    unit: 'Kg',
    product_type: 'Grain',
    maintain_batches: true,
    tally_stock_item_name: 'Wheat Flour',
  },
  {
    id: '3',
    name: 'Fertilizer NPK 10-26-26',
    kannada_name: 'ರಸಗೊಬ್ಬರ ಎನ್‌ಪಿಕೆ',
    hsn_code: '3105',
    unit: 'Bag',
    product_type: 'Fertilizer',
    maintain_batches: true,
    tally_stock_item_name: 'Fertilizer NPK',
  },
  {
    id: '4',
    name: 'Pesticide Spray',
    kannada_name: 'ಕೀಟನಾಶಕ ಸ್ಪ್ರೆ',
    hsn_code: '3808',
    unit: 'Liter',
    product_type: 'Pesticide',
    maintain_batches: false,
    tally_stock_item_name: 'Pesticide Spray',
  },
]

export const mockSalesInvoices: SalesInvoice[] = [
  {
    id: '1',
    invoice_number: 'INV-001',
    customer_id: '1',
    items: [
      {
        id: '1',
        product_id: '1',
        batch: 'BATCH-2024-001',
        quantity: 50,
        rate: 50,
        tally_price: 50,
        gst: 5,
      },
    ],
    total: 2625,
    status: 'synced',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '2',
    invoice_number: 'INV-002',
    customer_id: '2',
    items: [
      {
        id: '1',
        product_id: '2',
        batch: 'BATCH-2024-002',
        quantity: 100,
        rate: 30,
        tally_price: 30,
        gst: 5,
      },
    ],
    total: 3150,
    status: 'saved',
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '3',
    invoice_number: 'INV-003',
    customer_id: '3',
    items: [
      {
        id: '1',
        product_id: '3',
        batch: 'BATCH-2024-003',
        quantity: 25,
        rate: 120,
        tally_price: 120,
        gst: 5,
      },
    ],
    total: 3150,
    status: 'synced',
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: '4',
    invoice_number: 'INV-004',
    customer_id: '4',
    items: [
      {
        id: '1',
        product_id: '1',
        batch: 'BATCH-2024-004',
        quantity: 75,
        rate: 50,
        tally_price: 50,
        gst: 5,
      },
    ],
    total: 3937,
    status: 'saved',
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: '5',
    invoice_number: 'INV-005',
    customer_id: '5',
    items: [
      {
        id: '1',
        product_id: '2',
        batch: 'BATCH-2024-005',
        quantity: 60,
        rate: 30,
        tally_price: 30,
        gst: 5,
      },
    ],
    total: 1890,
    status: 'synced',
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: '6',
    invoice_number: 'INV-006',
    customer_id: '6',
    items: [
      {
        id: '1',
        product_id: '4',
        batch: 'BATCH-2024-006',
        quantity: 40,
        rate: 80,
        tally_price: 80,
        gst: 5,
      },
    ],
    total: 3360,
    status: 'saved',
    created_at: new Date(Date.now() - 518400000).toISOString(),
  },
]

export const mockSyncLogs: SyncLog[] = [
  {
    id: '1',
    type: 'success',
    message: 'Invoice INV-001 synced successfully',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '2',
    type: 'failed',
    message: 'Customer Ledger not found in Tally',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    error: 'Ledger does not exist in Tally',
  },
  {
    id: '3',
    type: 'success',
    message: 'Product stock updated',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
  },
]

// Purchase Invoices
export const mockPurchaseInvoices = [
  {
    id: 'PI-001',
    invoice_number: 'PUR-001',
    supplier_id: '1',
    supplier_name: 'AgroSupply Ltd',
    items: 'Organic Rice - 100 Kg',
    total: 5000,
    status: 'synced',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'PI-002',
    invoice_number: 'PUR-002',
    supplier_id: '2',
    supplier_name: 'FarmPro Traders',
    items: 'Fertilizer NPK - 50 Bag',
    total: 6000,
    status: 'saved',
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'PI-003',
    invoice_number: 'PUR-003',
    supplier_id: '3',
    supplier_name: 'Green Harvest Supplies',
    items: 'Wheat Flour - 80 Kg',
    total: 2400,
    status: 'synced',
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'PI-004',
    invoice_number: 'PUR-004',
    supplier_id: '4',
    supplier_name: 'Organic Seeds Co',
    items: 'Pesticide - 30 Liter',
    total: 4500,
    status: 'pending',
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'PI-005',
    invoice_number: 'PUR-005',
    supplier_id: '5',
    supplier_name: 'Premium Fertilizers',
    items: 'Organic Fertilizer - 100 Kg',
    total: 7500,
    status: 'synced',
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'PI-006',
    invoice_number: 'PUR-006',
    supplier_id: '6',
    supplier_name: 'Bio Solutions Ltd',
    items: 'Bio Insecticide - 20 Liter',
    total: 3800,
    status: 'saved',
    created_at: new Date(Date.now() - 518400000).toISOString(),
  },
]

// Product Stock
export const mockProductStock = [
  {
    id: 'PS-001',
    product_name: 'Organic Rice',
    unit: 'Kg',
    quantity: 500,
    reorder_level: 100,
    status: 'Good',
    last_updated: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'PS-002',
    product_name: 'Wheat Flour',
    unit: 'Kg',
    quantity: 250,
    reorder_level: 150,
    status: 'Low',
    last_updated: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'PS-003',
    product_name: 'Fertilizer NPK',
    unit: 'Bag',
    quantity: 120,
    reorder_level: 50,
    status: 'Good',
    last_updated: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'PS-004',
    product_name: 'Pesticide Spray',
    unit: 'Liter',
    quantity: 45,
    reorder_level: 30,
    status: 'Good',
    last_updated: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'PS-005',
    product_name: 'Organic Fertilizer',
    unit: 'Kg',
    quantity: 80,
    reorder_level: 100,
    status: 'Critical',
    last_updated: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: 'PS-006',
    product_name: 'Bio Insecticide',
    unit: 'Liter',
    quantity: 60,
    reorder_level: 40,
    status: 'Good',
    last_updated: new Date(Date.now() - 21600000).toISOString(),
  },
]

// Ledgers
export const mockLedgers = [
  {
    id: 'LED-001',
    name: 'Rajesh Kumar',
    type: 'Customer',
    balance: 2625,
    opening_balance: 0,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'LED-002',
    name: 'Priya Sharma',
    type: 'Customer',
    balance: 3150,
    opening_balance: 5000,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'LED-003',
    name: 'AgroSupply Ltd',
    type: 'Supplier',
    balance: -5000,
    opening_balance: -2500,
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'LED-004',
    name: 'FarmPro Traders',
    type: 'Supplier',
    balance: -6000,
    opening_balance: 0,
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'LED-005',
    name: 'Gopal Reddy',
    type: 'Customer',
    balance: 3150,
    opening_balance: 2000,
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'LED-006',
    name: 'Green Harvest Supplies',
    type: 'Supplier',
    balance: -2400,
    opening_balance: -1000,
    created_at: new Date(Date.now() - 518400000).toISOString(),
  },
]

// Crop Purchase
export const mockCropPurchase = [
  {
    id: 'CP-001',
    crop_name: 'Organic Rice',
    quantity: 500,
    unit: 'Kg',
    price_per_unit: 50,
    total_price: 25000,
    farmer_name: 'Ramesh Kumar',
    date: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'CP-002',
    crop_name: 'Wheat',
    quantity: 300,
    unit: 'Kg',
    price_per_unit: 28,
    total_price: 8400,
    farmer_name: 'Suresh Nair',
    date: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'CP-003',
    crop_name: 'Maize',
    quantity: 250,
    unit: 'Kg',
    price_per_unit: 22,
    total_price: 5500,
    farmer_name: 'Hari Singh',
    date: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'CP-004',
    crop_name: 'Sugarcane',
    quantity: 1000,
    unit: 'Kg',
    price_per_unit: 8,
    total_price: 8000,
    farmer_name: 'Mohan Lal',
    date: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'CP-005',
    crop_name: 'Cotton',
    quantity: 200,
    unit: 'Kg',
    price_per_unit: 95,
    total_price: 19000,
    farmer_name: 'Karan Patel',
    date: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'CP-006',
    crop_name: 'Groundnut',
    quantity: 180,
    unit: 'Kg',
    price_per_unit: 60,
    total_price: 10800,
    farmer_name: 'Ajay Reddy',
    date: new Date(Date.now() - 518400000).toISOString(),
  },
]
